const services = [
  {
    idService: "201",
    serviceType: "electricidad",
    serviceName:
      "instalaciones electricas, residencial, comercial e industrial",
    serviceDetail:
      "Servicio de instalaciones electricas, residencial, comercial e industrial",
    serviceList: ["a", "b"],
    serviceImage: "s_electri_1",
  },
  {
    idService: "202",
    serviceType: "electricidad",
    serviceName: "instalación de swiches, tomas",
    serviceDetail: "Servicio de instalación de swiches,tomas",
    serviceList: ["a", "b"],
    serviceImage: "s_electri_2",
  },
  {
    idService: "203",
    serviceType: "electricidad",
    serviceName: "Instalación de ojo de Buey, lámparas y reflectores",
    serviceDetail:
      "Servicio de Instalación de ojo de Buey,lámparas y reflectores",
    serviceList: ["a", "b"],
    serviceImage: "s_electri_3",
  },
  {
    idService: "204",
    serviceType: "electricidad",
    serviceName: "Instalación de duchas electricas",
    serviceDetail: "Servicio de instalación de duchas electricas",
    serviceList: ["a", "b"],
    serviceImage: "s_electri_4",
  },
  {
    idService: "205",
    serviceType: "electricidad",
    serviceName: "Instalación y reparación de hornos y campanas extractoras",
    serviceDetail:
      "Servicio de instalación y reparación de hornos y campanas extractoras",
    serviceList: ["a", "b"],
    serviceImage: "s_electri_5",
  },
  {
    idService: "101",
    serviceType: "plomeria",
    serviceName: "Instalación y mantenimiento de sanitario",
    serviceDetail: "Servicio de instalación y mantenimiento de sanitario",
    serviceList: ["a", "b"],
    serviceImage: "s_plomeria_1",
  },
  {
    idService: "102",
    serviceType: "plomeria",
    serviceName: "Instalación y mantenimiento de lavamanos",
    serviceDetail: "Servicio de instalación y mantenimiento de lavamanos",
    serviceList: ["a", "b"],
    serviceImage: "s_plomeria_2",
  },
  {
    idService: "103",
    serviceType: "plomeria",
    serviceName: "Instalación de duchas",
    serviceDetail: "Servicio de instalación de duchas",
    serviceList: ["a", "b"],
    serviceImage: "s_plomeria_3",
  },
  {
    idService: "104",
    serviceType: "plomeria",
    serviceName: "Instalación de mezclador de ducha",
    serviceDetail: "Servicio de instalación de mezclador de ducha",
    serviceList: ["a", "b"],
    serviceImage: "s_plomeria_7",
  },
  {
    idService: "105",
    serviceType: "plomeria",
    serviceName:
      "Instalación de llaves de lavadero, registro, abasto y llave de paso",
    serviceDetail:
      "Servicio de instalación de llaves de lavadero, registro, abasto y llave de paso",
    serviceList: ["a", "b"],
    serviceImage: "s_plomeria_4",
  },
  {
    idService: "106",
    serviceType: "plomeria",
    serviceName: "Desmonte e instalación de sanitarios",
    serviceDetail: "Servicio de desmonte e instalación de sanitarios",
    serviceList: ["a", "b"],
    serviceImage: "s_plomeria_10",
  },
  {
    idService: "107",
    serviceType: "plomeria",
    serviceName: "Instalación y mantenimiento de lavaplatos",
    serviceDetail: "Servicio de instalación y mantenimiento de lavaplatos",
    serviceList: ["a", "b"],
    serviceImage: "s_plomeria_6",
  },
  {
    idService: "108",
    serviceType: "plomeria",
    serviceName: "Mantenimiento de todo tipo de grifería",
    serviceDetail: "Servicio de mantenimiento de todo tipo de grifería",
    serviceList: ["a", "b"],
    serviceImage: "s_plomeria_7",
  },
  {
    idService: "109",
    serviceType: "plomeria",
    serviceName: "Reparación de fugas de agua en PVC, cobre, polipropileno",
    serviceDetail: "Servicio de reparación de fugas de agua en PVC, cobre, polipropileno",
    serviceList: ["a", "b"],
    serviceImage: "s_plomeria_8",
  },
  {
    idService: "110",
    serviceType: "plomeria",
    serviceName: "Instalación de tuberías hidrosanitarias",
    serviceDetail: "Servicio de instalación de tuberías hidrosanitarias",
    serviceList: ["a", "b"],
    serviceImage: "s_plomeria_9",
  },
];

export default services;
